name: Snyk Security Scan

on:
  pull_request:
     branches:
      - main

jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions@master
        with:
          args: test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Snyk Container Security Test
        uses: snyk/actions/docker@master
        with:
          image: gcr.io/project-management-ci-cd/my-app:latest
          args: test
       
      - name: Run Snyk with severity filter
        uses: snyk/actions@master
        with:
          args: test --severity-threshold=high
        